### ISSUE TITLE
Allow import for side effects only

### ISSUE THREAD

**Issue by fstanis** [webpack-contrib/imports-loader#61]
There are modules which I want to import only for the side effects they provide - in this case I only really need `require("module");` and not `var module = require("module");` - would this make sense to add?

I was thinking of something like `void=module` resulting in dropping the `var`, but then it occurred this would mean only one of these would be possible (since we can't have duplicate keys). Perhaps something like `~module` would work? Happy to do a PR, if there are no objections.

**Comment by michael-ciniawsky** [comment]
What is the practical use case ?  Can you give an example ?

**Comment by jazdw** [comment]
As @fstanis said, for side effects. e.g. loading an AngularJS module which depends upon another. Loading the AngularJS module doesn't return anything it just makes the module available for using from the global `angular` object.

e.g. using `'imports-loader?angular-animate` results in code like `var angular-animate = require("angular-animate");` which wont work due to the dash in the variable name.

**Comment by Backfighter** [comment]
You can checkout the [inject-imports-loader](https://github.com/Backfighter/inject-imports-loader) I wrote which supports side-effect imports.
